name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: mkdir public
      - uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: 'bundle openapi.yml -o public/index.html'
#      - uses: actions/setup-node@v2
#        with:
#          node-version: '14'
#      - run: npm install @openapitools/openapi-generator-cli -g
#      - name: Generate
#        run: |
#          npx @openapitools/openapi-generator-cli generate \
#            -i openapi.yml \
#            -g html2 \
#            -o public/
      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
