name: Generate TypesScript

on:
  push:
    branches: [ main ]

jobs:
  typescript:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone dest repository
        uses: actions/checkout@v2
        with:
          repository: 'shantichat/chatnode-api-ts'
          token: ${{ secrets.API_TOKEN_GITHUB }}
          path: dest
      - run: ls -lah dest/src
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: Install generator 
        run: npm install --save-dev git+https://github.com/shantichat/openapi-typescript.git
      - name: Generate index.ts
        run: npx openapi-typescript openapi.yml --output dest/src/index.ts
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'dest'
          destination-github-username: 'shantichat'
          destination-repository-name: 'chatnode-api-ts'
          user-email: action@github.com
          target-branch: main
          commit-message: Generated src/index.ts
